export enum Environments {
  DEVELOPMENT = 'DEVELOPMENT',
  STAGING = 'STAGING',
  PRODUCTION = 'PRODUCTION',
  STAGING_ORDERS = 'STAGING_ORDERS',
  PRODUCTION_ORDERS = 'PRODUCTION_ORDERS',
  STAGING_ORDERS_NOT_LOGGED_IN = 'STAGING_ORDERS_NOT_LOGGED_IN',
  PRODUCTION_ORDERS_NOT_LOGGED_IN = 'PRODUCTION_ORDERS_NOT_LOGGED_IN',
}
