export default {
    TRANSAK_WIDGET_INITIALISED: 'TRANSAK_WIDGET_INITIALISED',
    TRANSAK_WIDGET_OPEN: 'TRANSAK_WIDGET_OPEN',
    TRANSAK_WIDGET_CLOSE_REQUEST: 'TRANSAK_WIDGET_CLOSE_REQUEST',
    TRANSAK_WIDGET_CLOSE: 'TRANSAK_WIDGET_CLOSE',
    TRANSAK_ORDER_CREATED: 'TRANSAK_ORDER_CREATED',
    TRANSAK_ORDER_CANCELLED: 'TRANSAK_ORDER_CANCELLED',
    TRANSAK_ORDER_FAILED: 'TRANSAK_ORDER_FAILED',
    TRANSAK_ORDER_SUCCESSFUL: 'TRANSAK_ORDER_SUCCESSFUL'
}